name: Run test playwright


trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest



jobs:
  - job: RunPlaywright
    steps:
      - task: UseNode@1
        inputs:
          version: '18.x' # string. Version. Default: 10.x.



      - task: Bash@3
        displayName: Show version
        inputs:
          targetType: inline
          script: |

            npm i

            npx playwright install




            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install -y  libwoff2dec.so.1.0.2 libvpx.so.7 libevent-2.1.so.7 libopus.so.0 libgstallocators-1.0  libgstapp-1.0.so.0    libgstpbutils-1.0.so  libgstaudio-1.0.so.0  libgstgl-1.0.so.0     libgsttag-1.0.so.0    libgstvideo-1.0.so.0  libgstcodecparsers-1  libgstfft-1.0.so.0    libharfbuzz-icu.so.0  libhyphen.so.0  libmanette-0.2.so.0   libflite.so.1         libflite_usenglish.s  libflite_cmu_graphem  libflite_cmu_graphem  libflite_cmu_indic_l  libflite_cmu_indic_l  libflite_cmulex.so.1  libflite_cmu_time_a

          


      

      - task: Bash@3
        displayName: Show txt
        inputs:
          targetType: inline
          script: |

            node 1.js

            cat ./1.txt